### ISSUE TITLE
Validad Existencia de ExportDomain, antes de iniciar cualquier proceso.

### ISSUE THREAD

**Issue by xandradx** [dbinary/oVirtVMBackup#1]
Activating Export Domain LabExport1                                                                                                                                                           |
Different Export Attached                                                                                                                                                                     |
waiting for maintenance Storage... |Detach OK                                                                                                                                                 |
Traceback (most recent call last):                                                                                                                                                            |
  File "backup.py", line 99, in <module>                                                                                                                                                      |
    main()                                                                                                                                                                                    |
  File "backup.py", line 95, in main                                                                                                                                                          |
    description=description, export_domain=export_domain                                                                                                                                      |
  File "backup.py", line 55, in export                                                                                                                                                        |
    conn.active_export(vm=vm_name, export_name=export_domain)                                                                                                                                 |
  File "/opt/OvirtVMBackup/ovirtvmbackup/ovirtbackup.py", line 227, in active_export                                                                                                          |
    self.attach_export(dc.id, export_name)                                                                                                                                                    |
  File "/opt/OvirtVMBackup/ovirtvmbackup/ovirtbackup.py", line 203, in attach_export                                                                                                          |
    if self.api.datacenters.get(id=dc_id).storagedomains.add(self.api.storagedomains.get(export_ok)):                                                                                         |
  File "/usr/lib/python2.7/site-packages/ovirtsdk/infrastructure/brokers.py", line 10372, in add                                                                                              |
    body=ParseHelper.toXml(storagedomain),                                                                                                                                                    |
  File "/usr/lib/python2.7/site-packages/ovirtsdk/utils/parsehelper.py", line 48, in toXml                                                                                                    |
    "XML document." % entity_type.__name__                                                                                                                                                    |
Exception: The entity type "NoneType" can't be converted to XML because according to the XML schema it hasn't a top level element definition, thus it can't be used as the root of a valid XML|
 document.

**Comment by dbinary** [comment]
Agregado
